// <auto-generated />
namespace FestivalApp.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserFestivalRatingTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserFestivalRatingTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201907012303277_UserFestivalRatingTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
