//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivalApp.Services
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FestivalAppDB : DbContext
    {
        public FestivalAppDB()
            : base("name=FestivalAppDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Festival> Festivals { get; set; }
        public virtual DbSet<FestivalType> FestivalTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserFestivalType> UserFestivalTypes { get; set; }
    }
}
