//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestivalApp.Services
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFestivalType
    {
        public long UserId { get; set; }
        public long FestivalTypeId { get; set; }
    
        public virtual FestivalType FestivalType { get; set; }
    }
}
